spring:
#  datasource:
##    url: jdbc:h2:tcp://localhost/~/timeMachineLetter
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

#  jpa:
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        #        show_sql: true
#        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/time-machine-letter?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: null

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
# org.hibernate.type: trace